# Generated by Django 4.0.4 on 2022-05-07 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_donationarea_volunteer_gallery_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='donation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donation.donation'),
        ),
    ]
