# Generated by Django 4.0.4 on 2022-05-08 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0003_alter_gallery_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='adminremark',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='volunteerremark',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
