# Generated by Django 4.0.4 on 2022-05-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0005_alter_donation_donationarea_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orphange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.CharField(blank=True, max_length=50, null=True)),
                ('firstName', models.CharField(max_length=50)),
                ('contact', models.IntegerField(max_length=15)),
                ('email', models.EmailField(max_length=50)),
                ('orphanageImage', models.FileField(null=True, upload_to='')),
                ('pwd', models.CharField(max_length=20)),
                ('ownerImage', models.FileField(null=True, upload_to='')),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
