# Generated by Django 4.0.4 on 2022-05-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0006_orphange'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.CharField(blank=True, max_length=50, null=True)),
                ('firstName', models.CharField(max_length=50)),
                ('contact', models.IntegerField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
