# Generated by Django 4.0.4 on 2022-05-17 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0008_alter_orphange_firstname'),
    ]

    operations = [
        migrations.AddField(
            model_name='orphange',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orphange',
            name='firstName',
            field=models.CharField(max_length=50),
        ),
    ]
